services:
  - type: web
    name: insight-stream-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
